apiVersion: apps/v1
kind: Deployment
metadata:
  name: cour-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cour-service
  template:
    metadata:
      labels:
        app: cour-service
    spec:
      containers:
        - name: cour-service
          image: cour
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: cour-service
spec:
  selector:
    app: cour-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer