apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: video
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8010
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
  type: LoadBalancer